### ISSUE TITLE
Results

### ISSUE THREAD

**Issue by edogab33** [yrleegs/Pytorch-MSCRED#1]
Hello, did you manage to get the same results of the original paper? Is the algorithm working?

**Comment by yrleegs** [comment]
The algorithm itself works. Be careful with hyperparameter adjustments.

**Comment by edogab33** [comment]
> Be careful with hyperparameter adjustments.

Do you have any suggestion about the tuning? Did you also try to test the model on other data besides the original time series?

**Comment by yrleegs** [comment]
I've tested it on a given synthetic data set. Also, I don't have any advise anything except adjusting the various hyperparameters (batch size, threshold parameters, etc). I didn't test other datasets. Thank you.
